//DHLX
// DoomEd numbers for Doom

int T_PlayerStart1          =    1;
int T_PlayerStart2          =    2;
int T_PlayerStart3          =    3;
int T_PlayerStart4          =    4;
int T_BlueCard              =    5;
int T_YellowCard            =    6;
int T_SpiderMastermind      =    7;
int T_Backpack              =    8;
int T_ShotgunGuy            =    9;
int T_GibbedMarine          =   10;
int T_DeathmatchStart       =   11;
int T_GibbedMarineExtra     =   12;
int T_RedCard               =   13;
int T_TeleportDest          =   14;
int T_DeadMarine            =   15;
int T_Cyberdemon            =   16;
int T_CellPack              =   17;
int T_DeadZombieMan         =   18;
int T_DeadShotgunGuy        =   19;
int T_DeadDoomImp           =   20;
int T_DeadImp               =   20;
int T_DeadDemon             =   21;
int T_DeadCacodemon         =   22;
int T_DeadLostSoul          =   23;
int T_Gibs                  =   24;
int T_DeadStick             =   25;
int T_LiveStick             =   26;
int T_HeadOnAStick          =   27;
int T_HeadsOnAStick         =   28;
int T_HeadCandles           =   29;
int T_TallGreenColumn       =   30;
int T_ShortGreenColumn      =   31;
int T_TallRedColumn         =   32;
int T_ShortRedColum         =   33;
int T_Candlestick           =   34;
int T_Candelabra            =   35;
int T_HeartColumn           =   36;
int T_SkullColumn           =   37;
int T_RedSkull              =   38;
int T_YellowSkull           =   39;
int T_BlueSkull             =   40;
int T_EvilEye               =   41;
int T_FloatingSkull         =   42;
int T_TorchTree             =   43;
int T_BlueTorch             =   44;
int T_GreenTorch            =   45;
int T_RedTorch              =   46;
int T_Stalagtite            =   47;
int T_TechPillar            =   48;
int T_BloodyTwitch          =   49;
int T_Meat2                 =   50;
int T_Meat3                 =   51;
int T_Meat4                 =   52;
int T_Meat5                 =   53;
int T_BigTree               =   54;
int T_ShortBlueTorch        =   55;
int T_ShortGreenTorch       =   56;
int T_ShortRedTorch         =   57;
int T_Spectre               =   58;
int T_NonsolidMeat2         =   59;
int T_NonsolidMeat4         =   60;
int T_NonsolidMeat3         =   61;
int T_NonsolidMeat5         =   62;
int T_NonsolidTwitch        =   63;
int T_Archvile              =   64; // (Doom2)
int T_ChaingunGuy           =   65; // (Doom2)
int T_Revenant              =   66; // (Doom2)
int T_Fatso                 =   67; // (Doom2)
int T_Arachnotron           =   68; // (Doom2)
int T_HellKnight            =   69; // (Doom2)
int T_BurningBarrel         =   70; // (Doom2)
int T_PainElemental         =   71; // (Doom2)
int T_CommanderKeen         =   72; // (Doom2)
int T_HangNoGuts            =   73; // (Doom2)
int T_HangBNoBrain          =   74; // (Doom2)
int T_HangTLookingDown      =   75; // (Doom2)
int T_HangTSkull            =   76; // (Doom2)
int T_HangTLookingUp        =   77; // (Doom2)
int T_HangTNoBrain          =   78; // (Doom2)
int T_ColonGibs             =   79; // (Doom2)
int T_SmallBloodPool        =   80; // (Doom2)
int T_BrainStem             =   81; // (Doom2)
int T_SuperShotgun          =   82; // (Doom2)
int T_Megasphere            =   83; // (Doom2)
int T_WolfensteinSS         =   84; // (Doom2)
int T_TechLamp              =   85; // (Doom2)
int T_TechLamp2             =   86; // (Doom2)
int T_BossTarget            =   87; // (Doom2)
int T_BossBrain             =   88; // (Doom2)
int T_BossEye               =   89; // (Doom2)
int T_Shotgun               = 2001;
int T_Chaingun              = 2002;
int T_RocketLauncher        = 2003;
int T_PlasmaRifle           = 2004;
int T_Chainsaw              = 2005;
int T_BFG9000               = 2006;
int T_Clip                  = 2007;
int T_Shell                 = 2008;
int T_RocketAmmo            = 2010;
int T_Stimpack              = 2011;
int T_Medikit               = 2012;
int T_Soulsphere            = 2013;
int T_HealthBonus           = 2014;
int T_ArmorBonus            = 2015;
int T_GreenArmor            = 2018;
int T_BlueArmor             = 2019;
int T_InvulnerabilitySphere = 2022;
int T_Berserk               = 2023;
int T_BlurSphere            = 2024;
int T_RadSuit               = 2025;
int T_Allmap                = 2026;
int T_Column                = 2028;
int T_ExplosiveBarrel       = 2035;
int T_Infrared              = 2045;
int T_RocketBox             = 2046;
int T_Cell                  = 2047;
int T_ClipBox               = 2048;
int T_ShellBox              = 2049;
int T_DoomImp               = 3001;
int T_Imp                   = 3001;
int T_Demon                 = 3002;
int T_BaronOfHell           = 3003;
int T_ZombieMan             = 3004;
int T_Cacodemon             = 3005;
int T_LostSoul              = 3006;



